#pragma once

#define CHUNK_SIZE_X 32
#define CHUNK_SIZE_Y 96
#define CHUNK_SIZE_Z 32

#define RENDER_CHUNK_SIZE_X 32
#define RENDER_CHUNK_SIZE_Y 48
#define RENDER_CHUNK_SIZE_Z 32

#define CHUNK_RENDER_MESH_COUNT (CHUNK_SIZE_Y / RENDER_CHUNK_SIZE_Y)