#pragma once

#define CHUNK_SIZE_X 16
#define CHUNK_SIZE_Y 96
#define CHUNK_SIZE_Z 16

#define RENDER_CHUNK_SIZE_X 16
#define RENDER_CHUNK_SIZE_Y 96
#define RENDER_CHUNK_SIZE_Z 16

#define CHUNK_RENDER_MESH_COUNT (CHUNK_SIZE_Y / RENDER_CHUNK_SIZE_Y)

#define WATER_BLOCK_RESERVED_ID 128